# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrpc2.proto\x12\x07rpc2Pkg\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\tMultCoord\x12\x0e\n\x06values\x18\x01 \x03(\x01\x32\x46\n\x07RPCDemo\x12;\n\rGetMultCoords\x12\x16.google.protobuf.Empty\x1a\x12.rpc2Pkg.MultCoordB\x07\xaa\x02\x04rpc2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\004rpc2'
  _MULTCOORD._serialized_start=52
  _MULTCOORD._serialized_end=79
  _RPCDEMO._serialized_start=81
  _RPCDEMO._serialized_end=151
# @@protoc_insertion_point(module_scope)
