# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrpc/rpc.proto\x12\x0bgrpcWrapper\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\x1f\n\tMultCoord\x12\x12\n\x06values\x18\x01 \x03(\x01\x42\x02\x10\x01\x32g\n\x07RPCDemo\x12\\\n\rGetMultCoords\x12\x16.google.protobuf.Empty\x1a\x16.grpcWrapper.MultCoord\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/echoPosition:\x01*B&Z$example.com/rest-gateway-demo/protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$example.com/rest-gateway-demo/protos'
  _MULTCOORD.fields_by_name['values']._options = None
  _MULTCOORD.fields_by_name['values']._serialized_options = b'\020\001'
  _RPCDEMO.methods_by_name['GetMultCoords']._options = None
  _RPCDEMO.methods_by_name['GetMultCoords']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/echoPosition:\001*'
  _MULTCOORD._serialized_start=89
  _MULTCOORD._serialized_end=120
  _RPCDEMO._serialized_start=122
  _RPCDEMO._serialized_end=225
# @@protoc_insertion_point(module_scope)
